# Rules: https://github.com/sasstools/sass-lint/tree/master/docs/rules

options:
  formatter: stylish
files:
  include: 'assets/src/sass/**/*.scss'
  ignore: 'assets/src/sass/vendor/**/*.scss'
rules:
  class-name-format:
    - 2
    - convention: hyphenatedbem
    - allow-leading-underscore: false
  clean-import-paths: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  force-attribute-nesting: 0
  function-name-format: 0
  hex-length: 0
  hex-notation:
    - style: lowercase
  indentation:
    - 2
    -
      size: 2
  leading-zero: 0
  max-line-length:
    - 1
    - length: 100
  mixins-before-declarations: 0
  nesting-depth:
    - 1
    - max-depth: 3
  no-color-literals: 0
  no-css-comments: 0
  no-duplicate-properties: 1
  no-trailing-whitespace: 1
  no-trailing-zero: 1
  no-ids: 2
  no-qualifying-elements: 0
  no-vendor-prefixes:
    - 2
    - ignore-non-standard: true
  one-declaration-per-line: 1
  quotes:
    - 1
    - style: single
  property-sort-order: 0
  pseudo-element: 0
  space-after-colon: 1
  space-after-comma: 1
  space-around-operator: 1
  space-before-colon: 1
  space-between-parens: 1
  url-quotes: 0
